# File: .github/workflows/workflow.yml

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - uses: lauchacarro/Azure-Storage-Action@v1.0
      with:
        enabled-static-website: 'true'
        folder: '$web'
        blob-container-name: '$web'
        connection-string: ${{ secrets.CONNECTION_STRING }}